project:
  type: website
  output-dir: docs

website:
  title: "Y'all ready for this?: Construct validation of a readiness to train scale"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - FAQ.qmd  
        
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual
